Add Azure and Log Analytics setup instructions
CrowdStrike/falcon-integration-gateway pull request #31
Opened 2021-04-12 19:09 UTC by kylesmartin

I added instructions to docs/aks/README.md for setting up a Log Analytics workspace and getting the proper credentials.

2021-04-12 20:02 UTC, redhatrises requested changes

2021-04-12 20:02 UTC, redhatrises commented on docs/aks/README.md
> +Create a new Log Analytics workspace and assign it to your resource group. (Home > Log Analytics workspaces > Create)
```suggestion
1. Create a new Log Analytics workspace by selecting `Log Analytics workspaces`. You might have to search for it as a resource if it is not in your home menu.
1. Select `New`
1. Select the resource group that was previously created and enter a name under `Instance details`
1. Select `Review + Create`
1. Select `Create`

ssign it to your resource group. (Home > Log Analytics workspaces > Create)
```

2021-04-13 10:14 UTC, isimluk approved these changes
Thanks!

2021-04-14 08:49 UTC, isimluk commented on docs/aks/README.md
> +Create a new Log Analytics workspace and assign it to your resource group. (Home > Log Analytics workspaces > Create)
`ssign` above may be a typo

2021-04-14 08:49 UTC, isimluk commented
Guys, I am eager to merge this. Both of your versions are fine with me. :four_leaf_clover:

2021-04-14 15:18 UTC, kylesmartin commented on docs/aks/README.md
> +Create a new Log Analytics workspace and assign it to your resource group. (Home > Log Analytics workspaces > Create)
Fixed the typo

2021-04-14 15:19 UTC, kylesmartin commented
I think everything is good to merge now.

2021-04-14 15:29 UTC, redhatrises commented on docs/aks/README.md
> +Assign it to your resource group. (Home > Log Analytics workspaces > Create)
I think these lines need to be dropped. They appear to be duplicates of the instructions in line 28-32, but once they are, I think we should merge!

2021-04-14 15:50 UTC, merged